name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/*
  workflow_dispatch:

jobs:
  run-and-store:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker container and store SQLite
        id: run_container
        run: |
          docker run --name my-app-container \
          -v ./out/:/app/out/ \
          ghcr.io/${{ github.repository }}/my-app:latest \
          run_scrap.sh | tee result.log
          echo outfile=$(tail -1 result.log) >> $GITHUB_ENV

      - name: Store SQLite database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gupy_from_csv.sqlite
          path: ${{ github.workspace }}/${{ env.outfile }}

      - name: Get Artifact URL
        id: get-artifact-url
        run: |
          echo "url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" >> $GITHUB_ENV

      - name: Prepare HTML for GitHub Pages
        run: |
          mkdir -p docs
          sed -e "s/YOUR_USERNAME/${{ github.repository_owner }}/g" \
              -e "s/YOUR_REPO_NAME/${{ github.event.repository.name }}/g" \
              -e "s/LATEST_ARTIFACT_ID/${{ artifact-id }}/g" \
              sqlpage.html > ./docs/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
