name: Data Scraping Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Make scripts executable
        run: |
          chmod +x run_scrap.sh create_sqlite_from_csv.sh

      - name: Run the data scraping script
        run: |
          ./run_scrap.sh out/

      - name: Upload SQLite database as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sqlite-database
          path: out/*.db

