name: Data Scraping Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Make scripts executable
        run: |
          chmod +x run_scrap.sh create_sqlite_from_csv.sh

      - name: Run the data scraping script
        run: |
          ./run_scrap.sh out/

      - name: Upload SQLite database as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sqlite-database
          path: out/*.db

      - name: Generate HTML page
        run: |
          mkdir -p html
          cat <<<EOF > html/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>SQLite Viewer</title>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.6.2/sql-wasm.js"></script>
          </head>
            <body>
              <h1>SQLite Database Viewer</h1>
              <input type="file" id="file-input" />
              <div id="output"></div>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3
        with:
          build_dir: html
