name: Data Scraping Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Run the Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}/out:/app/out my-python-app

      - name: Upload SQLite database as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sqlite-database
          path: out/*.db

      - name: Generate HTML page
        run: |
          mkdir -p html
          cat <<EOF > html/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>SQLite Viewer</title>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.6.2/sql-wasm.js"></script>
          </head>
          <body>
              <h1>SQLite Database Viewer</h1>
              <input type="file" id="file-input" />
              <div id="output"></div>
              <script>
                  document.getElementById('file-input').addEventListener('change', async function(event) {
                      const file = event.target.files[0];
                      if (!file) return;

                      const arrayBuffer = await file.arrayBuffer();
                      const sql = await initSqlJs();
                      const db = new sql.Database(new Uint8Array(arrayBuffer));
                      
                      const result = db.exec('SELECT * FROM companies;');
                      const jobsResult = db.exec('SELECT * FROM jobs;');
                      
                      let html = '<h2>Companies</h2><table border="1"><tr><th>ID</th><th>Name</th><th>Logo URL</th><th>Career Page URL</th><th>Friendly Badge</th></tr>';
                      result[0].values.forEach(row => {
                          html += '<tr>' + row.map(cell => `<td>${cell}</td>`).join('') + '</tr>';
                      });
                      html += '</table>';

                      html += '<h2>Jobs</h2><table border="1"><tr><th>ID</th><th>Company ID</th><th>Title</th><th>Type</th><th>Department</th><th>Workplace City</th><th>Workplace State</th><th>Workplace Type</th></tr>';
                      jobsResult[0].values.forEach(row => {
                          html += '<tr>' + row.map(cell => `<td>${cell}</td>`).join('') + '</tr>';
                      });
                      html += '</table>';

                      document.getElementById('output').innerHTML = html;
                  });
              </script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3
        with:
          build_dir: html
